on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.67.0  # MSRV
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Create Cargo.lock file
        run: cargo generate-lockfile
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ hashFiles('Cargo.toml') }}
            cargo-registry

      - name: Build without features
        run: cargo build --no-default-features --verbose
      - name: Build with default features
        run: cargo build --verbose
      - name: Build examples
        run: cargo build --examples
