on: [push, pull_request]
name: Integration tests
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build STV-rs
        run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            target/release/stv-rs
          if-no-files-found: error
  integration_tests:
    needs: build
    strategy:
      matrix:
        file:
          - equal_preference/equal_preference
          - equal_preference/equal_preference_droop
          - equal_preference/equal_preference_equalize
          - random/rand_2x10
          - random/rand_5x4
          - random/rand_hypergeometric
          - recursive_descent/transfer
          - recursive_descent/transfer_is_blocked
          - ties/tie_break_explicit
          - ties/tie_break_implicit
          - vegetables
        parallel:
          - false
          - true
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: target/release/
      - name: Install Droop
        run: git clone https://github.com/jklundell/droop
      - name: Check STV-rs output (ballot from stdin)
        run: |
          chmod +x target/release/stv-rs
          target/release/stv-rs --arithmetic fixed9 --parallel=${{ matrix.parallel }} < testdata/${{ matrix.file }}.blt | diff -s testdata/${{ matrix.file }}.fixed9.log -
      - name: Check STV-rs output (ballot from CLI)
        run: |
          chmod +x target/release/stv-rs
          target/release/stv-rs --arithmetic fixed9 --parallel=${{ matrix.parallel }} --input testdata/${{ matrix.file }}.blt | diff -s testdata/${{ matrix.file }}.fixed9.log -
      - name: Check STV-rs output (equalized counting)
        run: |
          chmod +x target/release/stv-rs
          target/release/stv-rs --arithmetic fixed9 --parallel=${{ matrix.parallel }} --equalize --input testdata/${{ matrix.file }}.blt | diff -s testdata/${{ matrix.file }}.equalize.fixed9.log -
      - name: Check Droop output
        if: ${{ matrix.parallel == true }}
        run: |
          sed -i "s/Implementation: STV-rs/Droop package: droop v0.14/g" testdata/${{ matrix.file }}.fixed9.log
          python3 droop/Droop.py meek fixed precision=9 omega=6 defeat_batch=none testdata/${{ matrix.file }}.blt 2> droop.err | diff -s testdata/${{ matrix.file }}.fixed9.log -
          echo -n "" | diff -s - droop.err
  crash_fixed9_tests:
    needs: build
    strategy:
      matrix:
        file:
          - crashes/crash
          - crashes/minimal
          - crashes/rand_geometric
        parallel:
          - false
          - true
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: target/release/
      - name: Check STV-rs output
        run: |
          chmod +x target/release/stv-rs
          target/release/stv-rs --arithmetic fixed9 --parallel=${{ matrix.parallel }} --force-positive-surplus --input testdata/${{ matrix.file }}.blt | diff -s testdata/${{ matrix.file }}.fixed9.log -
      - name: Check STV-rs output (equalized counting)
        run: |
          chmod +x target/release/stv-rs
          target/release/stv-rs --arithmetic fixed9 --parallel=${{ matrix.parallel }} --force-positive-surplus --equalize --input testdata/${{ matrix.file }}.blt | diff -s testdata/${{ matrix.file }}.equalize.fixed9.log -
  crash_droop_tests:
    strategy:
      matrix:
        file:
          - crashes/crash
          - crashes/minimal
          - crashes/rand_geometric
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Droop
        run: git clone https://github.com/jklundell/droop
      - name: Check that Droop fails
        run: |
          python3 droop/Droop.py meek fixed precision=9 omega=6 defeat_batch=none testdata/${{ matrix.file }}.blt > droop.log 2> droop.err || true
          diff -s testdata/${{ matrix.file }}.droop.err droop.err
          echo -n "" | diff -s - droop.log
