on: [push, pull_request]
name: Integration tests
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build STV-rs
        run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            target/release/stv-rs
          if-no-files-found: error
  integration_tests:
    needs: build
    strategy:
      matrix:
        file:
          - equal_preference/equal_preference
          - equal_preference/equal_preference_droop
          - equal_preference/equal_preference_equalize
          - random/rand_2x10
          - random/rand_5x4
          - random/rand_hypergeometric
          - recursive_descent/transfer
          - recursive_descent/transfer_is_blocked
          - ties/tie_break_explicit
          - ties/tie_break_implicit
          - vegetables
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: target/release/
      - name: Install Droop
        run: git clone https://github.com/jklundell/droop
      - name: Check STV-rs output
        run: |
          chmod +x target/release/stv-rs
          target/release/stv-rs --arithmetic fixed9 < testdata/${{ matrix.file }}.blt | diff testdata/${{ matrix.file }}.fixed9.log -
      - name: Check STV-rs output (equalized counting)
        run: |
          chmod +x target/release/stv-rs
          target/release/stv-rs --equalize --arithmetic fixed9 < testdata/${{ matrix.file }}.blt | diff testdata/${{ matrix.file }}.equalize.fixed9.log -
      - name: Check Droop output
        run: |
          sed -i "s/Implementation: STV-rs/Droop package: droop v0.14/g" testdata/${{ matrix.file }}.fixed9.log
          python3 droop/Droop.py meek fixed precision=9 omega=6 defeat_batch=none testdata/${{ matrix.file }}.blt | diff testdata/${{ matrix.file }}.fixed9.log -
  crash_fixed9_tests:
    needs: build
    strategy:
      matrix:
        file:
          - crashes/crash
          - crashes/rand_geometric
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: target/release/
      - name: Check STV-rs output
        run: |
          chmod +x target/release/stv-rs
          target/release/stv-rs --arithmetic fixed9 --force-positive-surplus < testdata/${{ matrix.file }}.blt | diff testdata/${{ matrix.file }}.fixed9.log -
      - name: Check STV-rs output (equalized counting)
        run: |
          chmod +x target/release/stv-rs
          target/release/stv-rs --equalize --arithmetic fixed9 --force-positive-surplus < testdata/${{ matrix.file }}.blt | diff testdata/${{ matrix.file }}.equalize.fixed9.log -
