on: [push, pull_request]
name: Build and run tests
jobs:
  build_and_test:
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.67.0  # MSRV
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build without features
        run: cargo build --release --no-default-features --verbose
      - name: Tests without features
        run: cargo test --release --no-default-features --verbose

      - name: Build with default features
        run: cargo build --release --verbose
      - name: Tests with default features
        run: cargo test --release --verbose
