on: [push, pull_request]
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly

      - name: Create Cargo.lock file
        run: cargo generate-lockfile
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ hashFiles('Cargo.toml') }}
            cargo-registry

      - name: Check Cargo version
        run: cargo -V > cargo.version.txt
      - name: Cache Cargo target
        uses: actions/cache@v3
        with:
          path: target
          key: cargo-target-release-${{ hashFiles('cargo.version.txt') }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-target-release-${{ hashFiles('cargo.version.txt') }}-${{ hashFiles('Cargo.toml') }}
            cargo-target-release-${{ hashFiles('cargo.version.txt') }}

      - name: Tests without features
        run: cargo test --release --no-default-features --verbose
      - name: Tests with default features
        run: cargo test --release --verbose
