on: [push, pull_request]
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: Tests without features
        run: cargo test --release --no-default-features --verbose
      - name: Tests with default features
        run: cargo test --release --verbose
